<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-form :model="formData" ref="vForm" :rules="rules" label-position="top" label-width="80px" size="large"
    @submit.native.prevent>
    <div>  换行  </div>
    <div>  换行  </div>
    <div class="static-content-item" style="font-size: 40px">
      <div>教研系列专业职务 </div>
    </div>
    <div class="static-content-item">
      <el-divider direction="horizontal"></el-divider>
    </div>
    <div class="static-content-item">
      <div>一、基本情况</div>
    </div>
    <div class="table-container">
      <table class="table-layout">
        <tbody>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>姓名</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input69467"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input69467" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>工号</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input94101"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input94101" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>系（院）/中心</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input39759"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input39759" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" rowspan="3">
              <div class="static-content-item">
                <div>免冠照</div>
              </div>
            </td>
            <td class="table-cell" rowspan="3">
              <el-form-item label="" label-width="0" prop="pictureupload93431"
                class="small-margin-bottom label-center-align">
                <el-upload :file-list="pictureupload93431FileList" :headers="pictureupload93431UploadHeaders"
                  :data="pictureupload93431UploadData" list-type="picture-card" show-file-list :limit="1">
                  <template #default><i class="el-icon-plus"></i></template></el-upload>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>出生年月</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input25562"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input25562" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>国籍/民族</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input20620"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input20620" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>学科方向</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input116146"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input116146" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>职务</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="textarea75661" class="label-center-align">
                <el-input type="textarea" v-model="formData.textarea75661" rows="3"></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>现任职务日期</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="textarea106273" class="label-center-align">
                <el-input type="textarea" v-model="formData.textarea106273" rows="3"></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>申请事项</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="textarea18429" class="label-center-align">
                <el-input type="textarea" v-model="formData.textarea18429" rows="3"></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="8">
              <div class="static-content-item">
                <div>主要学历（从大学填起，包括国外学历，按时间倒序）</div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>起 止 年 月</div>
              </div>
            </td>
            <td class="table-cell" colspan="3">
              <div class="static-content-item">
                <div>学 校</div>
              </div>
            </td>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>系（专业）</div>
              </div>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>学 位</div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input36015"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input36015" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="3">
              <el-form-item label="" label-width="0" prop="input100474"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input100474" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input38749"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input38749" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input11767"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input11767" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input23991"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input23991" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="3">
              <el-form-item label="" label-width="0" prop="input45589"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input45589" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input103953"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input103953" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input100153"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input100153" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input103860" class="label-center-align">
                <el-input v-model="formData.input103860" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="3">
              <el-form-item label="" label-width="0" prop="input81121"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input81121" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input87205"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input87205" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input11679"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input11679" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input24606" class="label-center-align">
                <el-input v-model="formData.input24606" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="3">
              <el-form-item label="" label-width="0" prop="input106592" class="label-center-align">
                <el-input v-model="formData.input106592" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input18695" class="label-center-align">
                <el-input v-model="formData.input18695" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input94417" class="label-center-align">
                <el-input v-model="formData.input94417" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="8">
              <div class="static-content-item">
                <div>主要学术经历（包括国外经历，按时间倒序）</div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>起 止 年 月 </div>
              </div>
            </td>
            <td class="table-cell" colspan="4">
              <div class="static-content-item">
                <div>单 位</div>
              </div>
            </td>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>职 务（技术职务） </div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input23131"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input23131" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="4">
              <el-form-item label="" label-width="0" prop="input48471"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input48471" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input36467"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input36467" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input58024"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input58024" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="4">
              <el-form-item label="" label-width="0" prop="input49755"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input49755" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input37508"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input37508" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input18533"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input18533" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="4">
              <el-form-item label="" label-width="0" prop="input113730"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input113730" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input60413"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input60413" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input20952"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input20952" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="4">
              <el-form-item label="" label-width="0" prop="input21146"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input21146" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input62312"
                class="small-margin-bottom label-center-align">
                <el-input v-model="formData.input62312" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input36165" class="label-center-align">
                <el-input v-model="formData.input36165" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="4">
              <el-form-item label="" label-width="0" prop="input44391" class="label-center-align">
                <el-input v-model="formData.input44391" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input75734" class="label-center-align">
                <el-input v-model="formData.input75734" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="8">
              <div class="static-content-item">
                <div>重要学术任（兼）职（国内外重要学术组织（团体）或重要学术刊物等的任（兼）职）</div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>起 止 年 月 </div>
              </div>
            </td>
            <td class="table-cell" colspan="4">
              <div class="static-content-item">
                <div>单 位 名 称</div>
              </div>
            </td>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>职 务</div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input17660" class="label-center-align">
                <el-input v-model="formData.input17660" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="4">
              <el-form-item label="" label-width="0" prop="input24293" class="label-center-align">
                <el-input v-model="formData.input24293" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input81447" class="label-center-align">
                <el-input v-model="formData.input81447" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input110315" class="label-center-align">
                <el-input v-model="formData.input110315" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="4">
              <el-form-item label="" label-width="0" prop="input60271" class="label-center-align">
                <el-input v-model="formData.input60271" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input94857" class="label-center-align">
                <el-input v-model="formData.input94857" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input57493" class="label-center-align">
                <el-input v-model="formData.input57493" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="4">
              <el-form-item label="" label-width="0" prop="input34500" class="label-center-align">
                <el-input v-model="formData.input34500" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input67344" class="label-center-align">
                <el-input v-model="formData.input67344" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input62180" class="label-center-align">
                <el-input v-model="formData.input62180" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="4">
              <el-form-item label="" label-width="0" prop="input103780" class="label-center-align">
                <el-input v-model="formData.input103780" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input97094" class="label-center-align">
                <el-input v-model="formData.input97094" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input7249" class="label-center-align">
                <el-input v-model="formData.input7249" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="4">
              <el-form-item label="" label-width="0" prop="input94552" class="label-center-align">
                <el-input v-model="formData.input94552" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input107062" class="label-center-align">
                <el-input v-model="formData.input107062" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="static-content-item">
      <el-divider direction="horizontal"></el-divider>
    </div>
    <div class="static-content-item">
      <div>二 、 教育教学工作综述</div>
    </div>
    <div class="static-content-item">
      <div>（限 1000 字，包括教学理念，本科教育教学概述及研究生教育教学概述等）</div>
    </div>
    <el-form-item label="" label-width="0" prop="textarea21588" class="label-center-align">
      <el-input type="textarea" v-model="formData.textarea21588" rows="10" :maxlength="1000"
        :show-word-limit="true"></el-input>
    </el-form-item>
    <div class="static-content-item">
      <el-divider direction="horizontal"></el-divider>
    </div>
    <div class="static-content-item">
      <div>三、教学工作</div>
    </div>
    <div class="static-content-item">
      <div>3.1 课堂教学（列出近三年课程，按时间倒序）</div>
    </div>
    <div class="table-container">
      <table class="table-layout">
        <tbody>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>序号</div>
              </div>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>课程号</div>
              </div>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>课程名称</div>
              </div>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>授课学期</div>
              </div>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>课程总学时</div>
              </div>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>本人授课 总学时</div>
              </div>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>授课对 象及人 数</div>
              </div>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>课程类型</div>
              </div>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>学生评教情况 （前 5%， 前 50%，后50%， 后5%，无评教 结果</div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>1</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input61426" class="label-center-align">
                <el-input v-model="formData.input61426" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input29441" class="label-center-align">
                <el-input v-model="formData.input29441" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input108302" class="label-center-align">
                <el-input v-model="formData.input108302" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input37342" class="label-center-align">
                <el-input v-model="formData.input37342" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input58134" class="label-center-align">
                <el-input v-model="formData.input58134" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input55218" class="label-center-align">
                <el-input v-model="formData.input55218" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input41224" class="label-center-align">
                <el-input v-model="formData.input41224" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input57478" class="label-center-align">
                <el-input v-model="formData.input57478" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>2</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input64454" class="label-center-align">
                <el-input v-model="formData.input64454" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input83939" class="label-center-align">
                <el-input v-model="formData.input83939" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input63036" class="label-center-align">
                <el-input v-model="formData.input63036" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input79809" class="label-center-align">
                <el-input v-model="formData.input79809" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input98162" class="label-center-align">
                <el-input v-model="formData.input98162" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input101744" class="label-center-align">
                <el-input v-model="formData.input101744" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input106856" class="label-center-align">
                <el-input v-model="formData.input106856" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input24356" class="label-center-align">
                <el-input v-model="formData.input24356" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>3</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input36308" class="label-center-align">
                <el-input v-model="formData.input36308" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input98680" class="label-center-align">
                <el-input v-model="formData.input98680" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input60530" class="label-center-align">
                <el-input v-model="formData.input60530" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input51219" class="label-center-align">
                <el-input v-model="formData.input51219" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input75715" class="label-center-align">
                <el-input v-model="formData.input75715" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input47031" class="label-center-align">
                <el-input v-model="formData.input47031" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input54341" class="label-center-align">
                <el-input v-model="formData.input54341" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input18760" class="label-center-align">
                <el-input v-model="formData.input18760" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>4</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input93205" class="label-center-align">
                <el-input v-model="formData.input93205" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input35460" class="label-center-align">
                <el-input v-model="formData.input35460" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input20820" class="label-center-align">
                <el-input v-model="formData.input20820" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input22842" class="label-center-align">
                <el-input v-model="formData.input22842" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input106243" class="label-center-align">
                <el-input v-model="formData.input106243" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input89478" class="label-center-align">
                <el-input v-model="formData.input89478" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input23966" class="label-center-align">
                <el-input v-model="formData.input23966" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input73914" class="label-center-align">
                <el-input v-model="formData.input73914" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>5</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input20924" class="label-center-align">
                <el-input v-model="formData.input20924" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input108460" class="label-center-align">
                <el-input v-model="formData.input108460" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input86168" class="label-center-align">
                <el-input v-model="formData.input86168" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input70248" class="label-center-align">
                <el-input v-model="formData.input70248" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input83132" class="label-center-align">
                <el-input v-model="formData.input83132" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input39099" class="label-center-align">
                <el-input v-model="formData.input39099" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input36377" class="label-center-align">
                <el-input v-model="formData.input36377" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input115694" class="label-center-align">
                <el-input v-model="formData.input115694" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>6</div>
              </div>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input75861" class="label-center-align">
                <el-input v-model="formData.input75861" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input88942" class="label-center-align">
                <el-input v-model="formData.input88942" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input108408" class="label-center-align">
                <el-input v-model="formData.input108408" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input60455" class="label-center-align">
                <el-input v-model="formData.input60455" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input77199" class="label-center-align">
                <el-input v-model="formData.input77199" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input80908" class="label-center-align">
                <el-input v-model="formData.input80908" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input97592" class="label-center-align">
                <el-input v-model="formData.input97592" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input66351" class="label-center-align">
                <el-input v-model="formData.input66351" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="9">
              <div class="static-content-item">
                <div>小结（工作量是否达标，课程质量等）：</div>
              </div>
              <el-form-item label="" label-width="0" prop="textarea28325" class="label-center-align">
                <el-input type="textarea" v-model="formData.textarea28325" rows="5"></el-input>
              </el-form-item>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="static-content-item">
      <div>3.2 指导学生情况（列出近三年情况，按时间倒序）</div>
    </div>
    <div class="table-container">
      <table class="table-layout">
        <tbody>
          <tr>
            <td class="table-cell" colspan="9">
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>年度 </div>
              </div>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>研究生 姓名</div>
              </div>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>硕士或 博士</div>
              </div>
            </td>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>学位论文题目或研 究方向</div>
              </div>
            </td>
            <td class="table-cell">
              <div class="static-content-item">
                <div>毕业/在读</div>
              </div>
            </td>
            <td class="table-cell" colspan="3">
              <div class="static-content-item">
                <div>研究生获得的奖励 （包括在候选人指导下撰写论文获奖等 学术相关的奖励及学位论文获奖等） </div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input72927" class="label-center-align">
                <el-input v-model="formData.input72927" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input67558" class="label-center-align">
                <el-input v-model="formData.input67558" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input80341" class="label-center-align">
                <el-input v-model="formData.input80341" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input95954" class="label-center-align">
                <el-input v-model="formData.input95954" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input57531" class="label-center-align">
                <el-input v-model="formData.input57531" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="3">
              <el-form-item label="" label-width="0" prop="input72096" class="label-center-align">
                <el-input v-model="formData.input72096" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input89166" class="label-center-align">
                <el-input v-model="formData.input89166" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input62101" class="label-center-align">
                <el-input v-model="formData.input62101" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input20761" class="label-center-align">
                <el-input v-model="formData.input20761" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input104527" class="label-center-align">
                <el-input v-model="formData.input104527" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input41062" class="label-center-align">
                <el-input v-model="formData.input41062" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="3">
              <el-form-item label="" label-width="0" prop="input45483" class="label-center-align">
                <el-input v-model="formData.input45483" type="text" clearable></el-input>
              </el-form-item>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input34395" class="label-center-align">
                <el-input v-model="formData.input34395" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="3">
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input92528" class="label-center-align">
                <el-input v-model="formData.input92528" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="3">
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input55888" class="label-center-align">
                <el-input v-model="formData.input55888" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="3">
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input40549" class="label-center-align">
                <el-input v-model="formData.input40549" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="3">
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input52017" class="label-center-align">
                <el-input v-model="formData.input52017" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="3">
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input32613" class="label-center-align">
                <el-input v-model="formData.input32613" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="3">
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input65806" class="label-center-align">
                <el-input v-model="formData.input65806" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="3">
            </td>
          </tr>
          <tr>
            <td class="table-cell">
              <el-form-item label="" label-width="0" prop="input106479" class="label-center-align">
                <el-input v-model="formData.input106479" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="3">
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="table-container">
      <table class="table-layout">
        <tbody>
          <tr>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>近三年指导本 科生数量</div>
              </div>
            </td>
            <td class="table-cell" colspan="7">
              <div class="static-content-item">
                <div>本科生获得的校级及以上奖励/就业（升学）情况等</div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="table-cell" colspan="2">
              <el-form-item label="" label-width="0" prop="input34574" class="label-center-align">
                <el-input v-model="formData.input34574" type="text" clearable></el-input>
              </el-form-item>
            </td>
            <td class="table-cell" colspan="7">
              <el-form-item label="" label-width="0" prop="textarea65181" class="label-center-align">
                <el-input type="textarea" v-model="formData.textarea65181" rows="5"></el-input>
              </el-form-item>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="static-content-item">
      <el-divider direction="horizontal"></el-divider>
    </div>
    <div class="static-content-item">
      <div>四、教学学术</div>
    </div>
    <div class="static-content-item">
      <div>4.1 教学改革项目</div>
    </div>
    <div class="table-container">
      <table class="table-layout">
        <tbody>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>序号</div>
              </div>
            </td>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>项目名称</div>
              </div>
            </td>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>年度</div>
              </div>
            </td>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>项目来源</div>
              </div>
            </td>
            <td class="table-cell" colspan="3">
              <div class="static-content-item">
                <div>本人排名及主要贡献</div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="3">
            </td>
          </tr>
          <tr>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="3">
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="static-content-item">
      <div>4.2 教材</div>
    </div>
    <div class="table-container">
      <table class="table-layout">
        <tbody>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>序号</div>
              </div>
            </td>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>出版物名称</div>
              </div>
            </td>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>作者</div>
              </div>
            </td>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>出版社和出版时间 </div>
              </div>
            </td>
            <td class="table-cell" colspan="3">
              <div class="static-content-item">
                <div>校内外教材使用和推广情况 </div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="3">
            </td>
          </tr>
          <tr>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="3">
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="static-content-item">
      <div>4.3 教育教学研究论文</div>
    </div>
    <div class="table-container">
      <table class="table-layout">
        <tbody>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>序号</div>
              </div>
            </td>
            <td class="table-cell" colspan="4">
              <div class="static-content-item">
                <div>按论文题目、刊物名称、出版日期、 卷号、页号列出</div>
              </div>
            </td>
            <td class="table-cell" colspan="4">
              <div class="static-content-item">
                <div>所有作者排序 （申请人名字加粗，通讯作者名字上 用“*”标示，本人指导学生名字后用 “&”标示）</div>
              </div>
            </td>
            <td class="table-cell" colspan="3">
              <div class="static-content-item">
                <div>说明（如论文影响力、本 人贡献等</div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="4">
            </td>
            <td class="table-cell" colspan="4">
            </td>
            <td class="table-cell" colspan="3">
            </td>
          </tr>
          <tr>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="4">
            </td>
            <td class="table-cell" colspan="4">
            </td>
            <td class="table-cell" colspan="3">
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="static-content-item">
      <div>4.4 教学成果奖励（限填校级以上教学奖）</div>
    </div>
    <div class="table-container">
      <table class="table-layout">
        <tbody>
          <tr>
            <td class="table-cell">
              <div class="static-content-item">
                <div>序号</div>
              </div>
            </td>
            <td class="table-cell" colspan="3">
              <div class="static-content-item">
                <div>项目名称</div>
              </div>
            </td>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>奖励名称</div>
              </div>
            </td>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>奖励等级</div>
              </div>
            </td>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>本人排名</div>
              </div>
            </td>
            <td class="table-cell" colspan="2">
              <div class="static-content-item">
                <div>获奖时间 获批时间</div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="3">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="2">
            </td>
          </tr>
          <tr>
            <td class="table-cell">
            </td>
            <td class="table-cell" colspan="3">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="2">
            </td>
            <td class="table-cell" colspan="2">
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </el-form>

</template>

<script>
  export default {
    components: {},
    props: {},
    data() {
      return {
        formData: {
          input69467: "",
          input94101: "",
          input39759: "",
          pictureupload93431: null,
          input25562: "",
          input20620: "",
          input116146: "",
          textarea75661: "",
          textarea106273: "",
          textarea18429: "",
          input36015: "",
          input100474: "",
          input38749: "",
          input11767: "",
          input23991: "",
          input45589: "",
          input103953: "",
          input100153: "",
          input103860: "",
          input81121: "",
          input87205: "",
          input11679: "",
          input24606: "",
          input106592: "",
          input18695: "",
          input94417: "",
          input23131: "",
          input48471: "",
          input36467: "",
          input58024: "",
          input49755: "",
          input37508: "",
          input18533: "",
          input113730: "",
          input60413: "",
          input20952: "",
          input21146: "",
          input62312: "",
          input36165: "",
          input44391: "",
          input75734: "",
          input17660: "",
          input24293: "",
          input81447: "",
          input110315: "",
          input60271: "",
          input94857: "",
          input57493: "",
          input34500: "",
          input67344: "",
          input62180: "",
          input103780: "",
          input97094: "",
          input7249: "",
          input94552: "",
          input107062: "",
          textarea21588: "",
          input61426: "",
          input29441: "",
          input108302: "",
          input37342: "",
          input58134: "",
          input55218: "",
          input41224: "",
          input57478: "",
          input64454: "",
          input83939: "",
          input63036: "",
          input79809: "",
          input98162: "",
          input101744: "",
          input106856: "",
          input24356: "",
          input36308: "",
          input98680: "",
          input60530: "",
          input51219: "",
          input75715: "",
          input47031: "",
          input54341: "",
          input18760: "",
          input93205: "",
          input35460: "",
          input20820: "",
          input22842: "",
          input106243: "",
          input89478: "",
          input23966: "",
          input73914: "",
          input20924: "",
          input108460: "",
          input86168: "",
          input70248: "",
          input83132: "",
          input39099: "",
          input36377: "",
          input115694: "",
          input75861: "",
          input88942: "",
          input108408: "",
          input60455: "",
          input77199: "",
          input80908: "",
          input97592: "",
          input66351: "",
          textarea28325: "",
          input72927: "",
          input67558: "",
          input80341: "",
          input95954: "",
          input57531: "",
          input72096: "",
          input89166: "",
          input62101: "",
          input20761: "",
          input104527: "",
          input41062: "",
          input45483: "",
          input34395: "",
          input92528: "",
          input55888: "",
          input40549: "",
          input52017: "",
          input32613: "",
          input65806: "",
          input106479: "",
          input34574: "",
          textarea65181: "",
        },
        rules: {},
        pictureupload93431FileList: [],
        pictureupload93431UploadHeaders: {},
        pictureupload93431UploadData: {},
      }
    },
    computed: {},
    watch: {},
    created() {},
    mounted() {},
    methods: {
      submitForm() {
        this.$refs['vForm'].validate(valid => {
          if (!valid) return
          //TODO: 提交表单
        })
      },
      resetForm() {
        this.$refs['vForm'].resetFields()
      }
    }
  }

</script>

<style lang="scss">
  .el-input-number.full-width-input,
  .el-cascader.full-width-input {
    width: 100% !important;
  }

  .el-form-item--medium {
    .el-radio {
      line-height: 36px !important;
    }

    .el-rate {
      margin-top: 8px;
    }
  }

  .el-form-item--small {
    .el-radio {
      line-height: 32px !important;
    }

    .el-rate {
      margin-top: 6px;
    }
  }

  .el-form-item--mini {
    .el-radio {
      line-height: 28px !important;
    }

    .el-rate {
      margin-top: 4px;
    }
  }

  .clear-fix:before,
  .clear-fix:after {
    display: table;
    content: "";
  }

  .clear-fix:after {
    clear: both;
  }

  .float-right {
    float: right;
  }

  .small-margin-bottom.el-form-item {
    margin-bottom: 3px;
  }

</style>

<style lang="scss" scoped>
  div.table-container {
    table.table-layout {
      width: 100%;
      table-layout: fixed;
      border-collapse: collapse;

      td.table-cell {
        display: table-cell;
        height: 100px;   //格子的高度
        border: 1px solid #e1e2e3;
      }
    }
  }

  div.tab-container {}

  .label-left-align ::v-deep .el-form-item__label {
    text-align: left;
  }

  .label-center-align ::v-deep .el-form-item__label {
    text-align: center;
  }

  .label-right-align ::v-deep .el-form-item__label {
    text-align: right;
  }

  .custom-label {}

  .static-content-item {
    min-height: 20px;
    font-size: 18px;
    display: flex;
    align-items: center;

    ::v-deep .el-divider--horizontal {
      margin: 0;
    }
  }
</style>